### PR TITLE
updated readme file

### PR DESCRIPTION
**Pull request by BusyBee15**
Updated the readme file, so it will be easy for other developers who wants to contribute to the project

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @BusyBee15, I'll review the changes right away.

**Comment by BusyBee15** [comment]
> Thanks @BusyBee15, I'll review the changes right away.

@vanessa-cooper lint check is failing, what should I do

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "package-lock.json" from your PR and use yarn instead.

**Comment by BusyBee15** [comment]
I'll open a fresh PR

**Comment by BusyBee15** [comment]
@vanessa-cooper I did delete the "package-lock.json" and  ran "yarn import", but still getting the same error . Please help resolve this issue.

**Pull request closed without merging**
